sudo: false
before_script:
- mkdir /home/travis/bin
- curl -L https://github.com/yihui/ubuntu-bin/releases/download/latest/pandoc.tar.gz
  | tar xvz -C /home/travis/bin
- export PATH="$PATH:/home/travis/bin"
script: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  make &&
  pip install --user ghp-import &&
  ghp-import -n out &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
addons:
  apt:
    packages:
    - texlive-full
env:
  global:
  - secure: VcC4mvtgbwSk2LT6gUfcWyrOP1h0aoJvngaDwpAj2ZiKT7UzOIjzQ84raheWuXj01k0mrNXBl4S3j/CjeWT2/j3DWofkzCLtQ9xQqlok01lsEJ46dqkCfxZUo8lg7clICs5AdzlDVn68nCVHCLjqo9U3pHmZalBzD8lQukqROwRzXkmpnPy/ZiooF6i/VjrCvw1d7tsLGKS/elevT6dAJNqs8o3NzEbKI+uWd5BzEv0tHHAlnBB0nx7WxDpeiPCOEgKHpqdjcBtYRJHZ3Z4jIpjs6qDT/WFR7Bhzt2gCkBn3MRIBppX7aKzbAAicCCI28bNgbzuFU7idn8MC4WS1mA4Os3d+PmUUtuTLlN8y02LHF7XZKspVE3LxOLMYN0+1XYMsTaNJFUYvptFLqnyKHW8UYulyiOA0nfZZSkc+6KYupav7+g+JXz5mzjzhl+Sldm5ScULWznImGZxRcYVc8IFQ3aP+gNzv6hCOTYXKnVAicxLMnhkmFGnpqiuDxo/Dln7s8zotdKrEAXjWwkRmECYrLQOeDoJi0LVXjabG9tLRPGlC0PMZIBfZI3iM7LkiaKgeQ20FhUz4RwZVkWNJQkQxcZlHXsXlJdS5RmNWMuJU4UjSQgm8Vhjq/hsEcNjyoUc70zDrW+T6tMa43JjpnOX31OOXsoWdlozqkH1uCwE=
  - secure: dbGCIcwnPuYZTLfQ33wWaUix5KN1wBA3x546NP2CSZTrGkol+bO4Ird/rbqjEqW/eN9XYMahezZCOUcL8g8yVbUA8vG96mhflvlfPoJhPJKtyVc49DmIcJvL4EdEf7iXH+E4tsSiRaQEDzTne42Eekf/Lkl1Az0Ks6iDpsZyS0ztED/qqjYRFlqQX74BP5Vsg+V7ILRA4VBHlC10oDgMzTTfWiuvOE1qo+sE/+xjvvKiLP26f1R/s466nqRKw173MKL2GczEsFN+FHrqLRWQfirgkprIdRwWhxyoEi8HaWAV3jdMKjdp6V1R8oOqedFyA9Y4UCqM+AB8Bqzc/s4tA5IP0XUh8LEZAuYo8iMqejLabWiYDWWoLpCboLeurnBfn9+cSDDtD61TPXJdiDNkotT7JEm9BF6EbfMBbg5XtVizOUfpjcydJShkyXk14+u8xCJiE4HpfbDTXvzDH4WjlxXTBZK5C0Pth7xyZ7uKwyVXZdaEv0L7jDFL3w8goXLJ7uQx8lqOYG+nmanalLQuLUGDd6vi3jN3ruEGOHBlL+DbO9XMvRuzVdk6hspZ8ZojfDSPWWf2ViK8R05jueImePHuMGHw85UzxK6EeTcH21Kr6Su7nmmmBJnLYKxs0Kpp3IYeWIFqHereHySNkUIuFHROMRtPpN8ehxwV12QsvXU=
  - secure: TIx7+4HZruaAACQp8fWUYaXyZdcoF6B2cgufoJ2uhZuT9HK53cKepPftiH3vlwjHxS/YjlAFrgB8b2qyDgjGTYvaRZfcx8KeFmSC+yM6NuZbRhlfRL7/wlvtHmqWWPfTDj5TYBagY1hiQk0Ztijvemg/G7X4aeQlb8agW0ghJWeIwZvPq/otU/VxPJZiPF4qceoO10q4Alc6/FyIwJAj6cGMg+M0VAYEkS5Sjf1GvNUjvaylZpetSOfIXY1BkooQWSAdpC0cz1NcsDoqnQ6fJNA7agtDj9W+hDUJENJTi4VIrMgWGX1usuzVGAj9itChnBY45VDma/vGizF+0QadVrXy0UPyM1g4ekC5uMvcgRLOoA+z2tAruV9ooCqOw+y1Ioc3CDMiZ4tVC8bMH0ib+Q4IANrXtcULuh37KAkMPtcgDUEc5lgxZJGuN+dxUluZgvAqnyBJbUAo4rCa+dY48NiVu/Cq0Xgy/rsX+bAwPfaRJxeAmPfV7DtElM8adHEHd0VILk/mpujZgd87SnuL2mDp1tdV0E/mA8gJZR4VBOqotX/qATtr9HJY1t80Dk4MQZdz2KWe71WIi0WmunJMrZ8S/NQiUBYcbC3w1ga8/Zh64PZIBoF+YGjTKGdl4NLk8CSm9V3SeJvlTMopf4TT27MmG5vvmHcSt7lkU+ryljc=
