sudo: false
before_script:
- mkdir /home/travis/bin
- curl -L https://github.com/yihui/ubuntu-bin/releases/download/latest/pandoc.tar.gz
  | tar xvz -C /home/travis/bin
- export PATH="$PATH:/home/travis/bin"
- if ["$TRAVIS_PULL_REQUEST" != "false"]; then
    TRAVIS_COMMIT_RANGE="FETCH_HEAD...$TRAVIS_BRANCH"
  fi
- git diff --name-only $TRAVIS_COMMIT_RANGE | grep 'README.md' || {
        echo "No build. Only README.md changed"
        exit
        }
script: |
  [ $TRAVIS_PULL_REQUEST = false ] &&
  make &&
  pip install --user ghp-import &&
  ghp-import -n out &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
addons:
  apt:
    packages:
    - texlive-full
env:
  global:
    secure: XnsAFp/NYpmDtMqNZcWoL8nUJMrB2QIQnw8u/t0x7Qn8zRjiAqKAA0snfzGTtDyfRvIxM7oYQko0sh0/zkN7ktp9xR8Ct47Tf1AWrBV6mCrZGCAGBORx5B1xdHC8goolsOMaCSj9PqfmLxfmQi1MFajWZ/zSUHvFVxlutVARC0L3K/yT7Ewk7jQqF5U7Wzu5uCv4TYboSd3X0wuU69H2jkgk+lq1SBmVe/VKiiyOHqR0cFtIPg55Rtm7CeGj9LXSzI+8tCmhXoNGp4sQyzcX3zYQ26HD/FiPsUdzojlPY2eJFPJsRMiEeNZa0V+kVuj9wYL6V+LDW3zwMAjVfOX7hzarrGKBN1lVeVaIahoId0y0y5GfGoMMg9yGSQ2pn2CPi6078mLfP6Ga7Z9D7iqMv+wNMbd6Bt2oW7zEltEuH1R8ZdEX4Ua/Oipj0oyB4kv2P1sUlv4PDVpajCzJZ7RfEWlAv4x4ifPa9tAJfgd3tzoJxYG606RT9WHwmBzmWNzAPTBNu93a23mGKHJ7kYJy98RGyEc6IB3GE6Ymi+LzyZuPkkror8M0KyRWh6Wiu7QwXaKKmZ5vjbNMPX1YTRC1ROAHWJwrAVLhMGFa8xRSWAel5jzhemYGSo5C8hjgchURUBy2fT1+hrV9VrL8Z7aa6gvs906tEcTBjxYp5ujPLMw=
